# Obs frequencies func

In [30]:
def get_observable_frequencies(n):
    """
    Generates a list of lists of lists describing observable class frequencies for n samplings from n items.

    Args:
        n: The number of samplings and total items.

    Returns:
        A list of lists of lists. Each inner list of lists corresponds to a number of classes 'c' (from 2 to n).
        Each list within that is a sorted list of observable class frequencies for that 'c'.
    """
    result_list = []

    def get_partitions(remaining_sum, parts_needed, current_partition):
        if parts_needed == 0:
            if remaining_sum == 0:
                yield current_partition[:]  # Yield a copy of the current partition
            return
        for i in range(1, remaining_sum - (parts_needed - 1) + 1):
            if i > 0:
                current_partition.append(i)        
                yield from get_partitions(remaining_sum - i, parts_needed - 1, current_partition)
                current_partition.pop()  # Backtrack
    

    for c in range(2, n + 1):
        
        unique_frequency_sets = set()
        partitions = get_partitions(n, c, [])
        partitions = [p for p in partitions]

        for partition in partitions:
            frequencies = [round(p / n, 5) for p in partition] # Round to avoid floating point issues, 5 decimal places should be enough
            frequencies.sort()
            unique_frequency_sets.add(tuple(frequencies))

        unique_frequency_lists = [list(freq_tuple) for freq_tuple in unique_frequency_sets]
        result_list.append(unique_frequency_lists)

    return result_list
get_observable_frequencies(20)

[[[0.5, 0.5],
  [0.1, 0.9],
  [0.35, 0.65],
  [0.2, 0.8],
  [0.4, 0.6],
  [0.25, 0.75],
  [0.15, 0.85],
  [0.3, 0.7],
  [0.05, 0.95],
  [0.45, 0.55]],
 [[0.15, 0.2, 0.65],
  [0.05, 0.35, 0.6],
  [0.1, 0.2, 0.7],
  [0.05, 0.2, 0.75],
  [0.25, 0.3, 0.45],
  [0.15, 0.4, 0.45],
  [0.2, 0.35, 0.45],
  [0.3, 0.3, 0.4],
  [0.05, 0.4, 0.55],
  [0.1, 0.25, 0.65],
  [0.2, 0.2, 0.6],
  [0.2, 0.4, 0.4],
  [0.05, 0.25, 0.7],
  [0.15, 0.25, 0.6],
  [0.1, 0.45, 0.45],
  [0.25, 0.35, 0.4],
  [0.1, 0.1, 0.8],
  [0.05, 0.45, 0.5],
  [0.3, 0.35, 0.35],
  [0.2, 0.25, 0.55],
  [0.1, 0.3, 0.6],
  [0.05, 0.1, 0.85],
  [0.15, 0.3, 0.55],
  [0.25, 0.25, 0.5],
  [0.05, 0.3, 0.65],
  [0.05, 0.05, 0.9],
  [0.1, 0.15, 0.75],
  [0.15, 0.15, 0.7],
  [0.2, 0.3, 0.5],
  [0.1, 0.35, 0.55],
  [0.05, 0.15, 0.8],
  [0.15, 0.35, 0.5],
  [0.1, 0.4, 0.5]],
 [[0.05, 0.1, 0.2, 0.65],
  [0.05, 0.05, 0.05, 0.85],
  [0.1, 0.2, 0.35, 0.35],
  [0.1, 0.15, 0.15, 0.6],
  [0.05, 0.15, 0.35, 0.45],
  [0.05, 0.2, 0.3, 0.45],
  [0.05, 0.

In [2]:
def get_observable_frequencies(n):
    """
    Generates a list of lists of lists describing observable class frequencies for n samplings from n items.

    Args:
        n: The number of samplings and total items.

    Returns:
        A list of lists of lists. Each inner list of lists corresponds to a number of classes 'c' (from 2 to n).
        Each list within that is a sorted list of observable class frequencies for that 'c'.
    """
    result_list = []

    def get_partitions(remaining_sum, parts_needed, current_partition):
        if parts_needed == 0:
            if remaining_sum == 0:
                yield current_partition[:]  # Yield a copy of the current partition
            return
        for i in range(1, remaining_sum - (parts_needed - 1) + 1):
            if i > 0:
                current_partition.append(i)
                print("-----c",current_partition, remaining_sum, parts_needed)
                yield from get_partitions(remaining_sum - i, parts_needed - 1, current_partition)
                current_partition.pop()  # Backtrack
                print("-----p",current_partition)

    for c in range(2, n + 1):
        print("||||||||||||||||||||||||||||||||||||",c)
        unique_frequency_sets = set()
        partitions = get_partitions(n, c, [])
        partitions = [p for p in partitions]
        print("partitions-->", partitions)
        for partition in partitions:
            frequencies = [round(p / n, 5) for p in partition] # Round to avoid floating point issues, 5 decimal places should be enough
            frequencies.sort()
            unique_frequency_sets.add(tuple(frequencies))

        unique_frequency_lists = [list(freq_tuple) for freq_tuple in unique_frequency_sets]
        result_list.append(unique_frequency_lists)

    return result_list

get_observable_frequencies(5)

|||||||||||||||||||||||||||||||||||| 2
-----c [1] 5 2
-----c [1, 1] 4 1
-----p [1]
-----c [1, 2] 4 1
-----p [1]
-----c [1, 3] 4 1
-----p [1]
-----c [1, 4] 4 1
-----p [1]
-----p []
-----c [2] 5 2
-----c [2, 1] 3 1
-----p [2]
-----c [2, 2] 3 1
-----p [2]
-----c [2, 3] 3 1
-----p [2]
-----p []
-----c [3] 5 2
-----c [3, 1] 2 1
-----p [3]
-----c [3, 2] 2 1
-----p [3]
-----p []
-----c [4] 5 2
-----c [4, 1] 1 1
-----p [4]
-----p []
partitions--> [[1, 4], [2, 3], [3, 2], [4, 1]]
|||||||||||||||||||||||||||||||||||| 3
-----c [1] 5 3
-----c [1, 1] 4 2
-----c [1, 1, 1] 3 1
-----p [1, 1]
-----c [1, 1, 2] 3 1
-----p [1, 1]
-----c [1, 1, 3] 3 1
-----p [1, 1]
-----p [1]
-----c [1, 2] 4 2
-----c [1, 2, 1] 2 1
-----p [1, 2]
-----c [1, 2, 2] 2 1
-----p [1, 2]
-----p [1]
-----c [1, 3] 4 2
-----c [1, 3, 1] 1 1
-----p [1, 3]
-----p [1]
-----p []
-----c [2] 5 3
-----c [2, 1] 3 2
-----c [2, 1, 1] 2 1
-----p [2, 1]
-----c [2, 1, 2] 2 1
-----p [2, 1]
-----p [2]
-----c [2, 2] 3 2
-----c [2, 2, 1] 1 1
-----p [2,

[[[0.2, 0.8], [0.4, 0.6]],
 [[0.2, 0.2, 0.6], [0.2, 0.4, 0.4]],
 [[0.2, 0.2, 0.2, 0.4]],
 [[0.2, 0.2, 0.2, 0.2, 0.2]]]

In [3]:
def test():
    a = [1,2,3,4]
    yield a[:]

[x for x in test()]

[[1, 2, 3, 4]]

# Snp number probability

In [41]:
def snp_num_prob_gen(p, factor):
    probs = {2:1}
    for i in range(p,2,-1):
        probs[i] = 10 ** -(i+factor-2)
    
    total_prob = sum(probs.values())

    for i in probs.keys():
        probs[i] = probs[i] / total_prob

    return probs


snp_num_prob_gen(6, 0)


        



{2: 0.900009000090001,
 6: 9.00009000090001e-05,
 5: 0.0009000090000900009,
 4: 0.00900009000090001,
 3: 0.0900009000090001}

# poisson sampler

In [32]:
import numpy as np

def sample_truncated_poisson(lam, minimum, n):
    """
    Samples n numbers from a Poisson distribution with parameter lambda,
    with the constraint that no sampled number is lower than minimum.

    Parameters:
    lam (float or int): Lambda parameter of the Poisson distribution (rate parameter, must be non-negative).
    minimum (int): The minimum value allowed for the sampled numbers (must be a non-negative integer).
    n (int): The number of samples to generate.

    Returns:
    list: A list of n integers sampled from the truncated Poisson distribution.
    """
    if lam < 0:
        raise ValueError("Lambda parameter must be non-negative.")
    if minimum < 0 or not isinstance(minimum, int):
        raise ValueError("Minimum parameter must be a non-negative integer.")
    if n <= 0 or not isinstance(n, int):
        raise ValueError("Number of samples n must be a positive integer.")

    samples = []# Generate ploidy related class frequency distributions
    while len(samples) < n:
        sample = np.random.poisson(lam)
        if sample >= minimum:
            samples.append(sample)
    return samples

# Nitro bases sampler

In [28]:
import random

def sample_dna_bases(n):
    """
    Samples n DNA bases with diversity constraints.

    Args:
        n (int): The number of DNA bases to sample.

    Returns:
        list: A list of n DNA bases (strings 'A', 'T', 'C', 'G').

    Raises:
        ValueError: If n is not a positive integer or if n < 2.
    """
    # Input validation
    if not isinstance(n, int) or n <= 0: # Corrected to be n <= 0 as the constraint starts from n>=2
        raise ValueError("n must be a positive integer greater than or equal to 2.")
    if n < 2:
        raise ValueError("n must be greater than or equal to 2 to satisfy the diversity constraints.")


    bases = ['A', 'T', 'C', 'G']

    if 2 <= n <= 4:
        # Case 1: All bases must be different
        sampled_bases = random.sample(bases, n)
    elif n > 4:
        # Case 2: At least 4 bases must be different
        distinct_bases = random.sample(bases, 4)
        remaining_bases_count = n - 4
        additional_bases = random.choices(bases, k=remaining_bases_count) # Use choices for repetition
        sampled_bases = distinct_bases + additional_bases
        random.shuffle(sampled_bases) # Shuffle for randomness
    else: # Should not reach here due to validation, but just in case.
        raise ValueError("n value not handled by function logic (should be >= 2).") # More descriptive error

    return sampled_bases


# Example Usage and Testing (add this part after writing the function)

sample_dna_bases(5)



['C', 'A', 'T', 'C', 'G']

# Main test

In [ ]:
from random import choices
from collections import Counter
import numpy as np


def main():
    n_snps = 1000
    p = 6
    f = 0
    d = "poisson"
    lam = 10
    snp_num_prob = snp_num_prob_gen(p, f)

    snp_num_counts= Counter(choices(list(snp_num_prob.keys()),weights=snp_num_prob.values(), k = n_snps))
    
    print(snp_num_counts)

    # Generate ploidy related class frequency distributions
    
    obs_freqs = get_observable_frequencies(p)
    
    # Generate depth distributions per each snp num

    site_id = 0
    
    for snp_num,count in snp_num_counts.items():
        for depth in sample_truncated_poisson(lam, snp_num, count):
            random_snp_weights = choices(obs_freqs[snp_num-2], k=1)[0]
            dna_bases_site = sample_dna_bases(snp_num)
            #print(dna_bases_site,random_snp_weights)
            dna_bases_counts = Counter(choices(dna_bases_site,weights=random_snp_weights, k = depth))
            while len(set(dna_bases_counts.keys())) < len(set(dna_bases_site)):
                dna_bases_counts = Counter(choices(dna_bases_site,weights=random_snp_weights, k = depth))
            for base,count in dna_bases_counts.items():
                print(site_id,snp_num,base,count,depth,sep="\t")
            site_id += 1

    


    # Iterate over each of the previous distributions
        # Select a random possible state from the class frequencies
        # Select snp_num random bases for the SNPs (if 4 >= snp_num >= 2 at least snp_num bases must be different), if snp_num >4 atleast 4 bases must be different
        # Sample bases using as weights the  possible state from class frequencies
        # With the counts from the sampling:
            # Print:
                # The site number, for each snp one site
                # The Base that was sampled
                # The counts of that base
                # The 



main()

In [46]:
from random import choices

choices([1,2], weights = [0.9,0.1], k= 10)

[1, 1, 2, 1, 1, 1, 1, 1, 1, 1]

# Graph results

Graph runs, first a run with parameters:  
- python ../../snp_freq_sim.py --n_snps 10000 --p 2 --f 0 --lam 20 > test_01_p2_f0_10000.tsv


In [2]:
import pandas as pd
import plotly.express as px

data_01 = pd.read_csv("tests/test_01_p2_f0_10000.tsv", names = ["snp_id","snp_number","base","base_count","total_site_depth"], sep = "\t")
data_01["freq"] = data_01["base_count"] / data_01["total_site_depth"]

px.histogram(data_01, x="freq", nbins=1000,
                         title='Histogram of Column 6 (Column 4 / Column 5)',
                         labels={'column6': 'Column 6 Value (Column 4 / Column 5)'})


In [3]:
data_02 = pd.read_csv("tests/test_01_p4_f0_10000.tsv", names = ["snp_id","snp_number","base","base_count","total_site_depth"], sep = "\t")
data_02["freq"] = data_02["base_count"] / data_02["total_site_depth"]

px.histogram(data_02, x="freq", nbins=1000,
                         title='Histogram of Column 6 (Column 4 / Column 5)',
                         labels={'column6': 'Column 6 Value (Column 4 / Column 5)'})

In [4]:
data_03 = pd.read_csv("tests/test_01_p3_f0_10000.tsv", names = ["snp_id","snp_number","base","base_count","total_site_depth"], sep = "\t")
data_03["freq"] = data_03["base_count"] / data_03["total_site_depth"]

px.histogram(data_03, x="freq", nbins=1000,
                         title='Histogram of Column 6 (Column 4 / Column 5)',
                         labels={'column6': 'Column 6 Value (Column 4 / Column 5)'})

In [6]:
import numpy as np
np.random.rand(100, 2)

array([[0.60623175, 0.10480129],
       [0.45336573, 0.62950564],
       [0.70185008, 0.66646278],
       [0.21231899, 0.23735757],
       [0.47169831, 0.87993441],
       [0.53413272, 0.86698338],
       [0.07321943, 0.43682419],
       [0.72215524, 0.90771601],
       [0.67746032, 0.25107795],
       [0.52973013, 0.23910223],
       [0.46933805, 0.51281281],
       [0.9368885 , 0.89613907],
       [0.57045671, 0.20938265],
       [0.95915378, 0.00574067],
       [0.36514291, 0.25966124],
       [0.17264956, 0.13965766],
       [0.26545644, 0.95292368],
       [0.62890652, 0.02375111],
       [0.20126005, 0.97260651],
       [0.20421153, 0.51596344],
       [0.739556  , 0.83307927],
       [0.80804112, 0.84021283],
       [0.90023244, 0.49561932],
       [0.20769905, 0.91452926],
       [0.27227175, 0.27760288],
       [0.45382287, 0.37913137],
       [0.43118839, 0.35784844],
       [0.40516142, 0.71474585],
       [0.89917784, 0.72361679],
       [0.75580479, 0.88546767],
       [0.

In [20]:
t= np.random.rand(1,100)

hist,bins = np.histogram(t, bins=10,density= False)
print(hist,hist.sum())
print(hist/100, (hist/100).sum())

[10 11 12  8  7  6 10 12  9 15] 100
[0.1  0.11 0.12 0.08 0.07 0.06 0.1  0.12 0.09 0.15] 1.0


array([1.02238767])